### ISSUE TITLE
Multiple wildcard functionality in tiles not working.

### ISSUE THREAD

**Issue by Durango807** [ironmonk88/monks-module-wiki#2]
I encountered a bug that affects the behavior of wildcards in the file paths when using the "Play Sound File" action. This issue prevents foundry from playing the correct sound files when multiple wildcards are used in the same tile.

To replicate the issue:

Set up a tile with a dialog that has few landings which play sound files.
Use wildcards in the file path for the sound files, such as "sfx_library/swords/small/shortsword*.mp3"

Observed behavior:
After selecting an initial sound option, subsequent selections of different sounds continue to play the initial sound until the page is reloaded. The software does not play the correct sound files based on the current selection.

Further investigation revealed that this issue specifically occurs when wildcards are used in the file path. Instead of playing the appropriate sound file, the software only plays the first wildcard sound for any other wildcard, regardless of the filepath.

I think this issue affects wildcard paths for images as well.

Discord messages link: https://discord.com/channels/862414864692281386/862421211749154816/1126515690208239636

**Comment by Crowguard** [comment]
@Durango807 Please post issues on their respective module GitHubs; not here.

**Comment by Durango807** [comment]
@Crowguard Sorry, didn't realize. New to Github.
